version: "3.1"

services:

  backend:
    build: 
      context: ./backend
    image: "spotify-backend:1.0"
    ports: 
      - "3001:3001"
  
  frontend:
    build: 
      context: ./frontend
    image: "spotify-frontend:1.1"
    ports: 
      - "3000:3000"