name: Spotify Clone Workflow

on:
  push:
    branches: 
      - '*'

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Node 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Install Frontend Dependencies
      run: | 
        cd frontend
        npm ci

    - name: Install Backend Dependencies
      run: | 
        cd backend
        npm ci
    
    - name: Build
      run: | 
        cd frontend
        npm run build --if-present
    
    - name: Run Unit Tests
      run: | 
        cd frontend
        npm test
