name: Spotify Clone Workflow

on:
  push:
    branches: 
      - '*'

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: |
          backend/package-lock.json
          frontend/package-lock.json
        
    - name: Install Frontend Dependencies
      run: | 
        cd frontend
        npm ci

    - name: Install Backend Dependencies
      run: | 
        cd backend
        npm ci
    
    - name: Build
      run: | 
        cd frontend
        npm run build --if-present
    
    - name: Run Unit Tests
      run: | 
        cd frontend
        npm test
